# Generated by Django 5.2.5 on 2025-08-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('is_there_match', models.BooleanField()),
                ('match_time', models.DateTimeField()),
                ('players_num', models.IntegerField()),
            ],
            options={
                'db_table': 'clubs',
            },
        ),
    ]
