# Generated by Django 5.2.5 on 2025-08-31 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_clubs_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='match_time',
        ),
    ]
