# Generated by Django 5.2.5 on 2025-09-02 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_match'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='match',
            table='matches',
        ),
    ]
